name: plasmidsaurus-align
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - minimap2
  - samtools
  - bedtools
  - biopython
  - pandas
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - jupyter
  - jupyterlab
  - pip
